"""
oversampleqa: A diagnostic toolkit for validating oversampling methods.

This package implements validation methods for synthetic data generated by
oversampling techniques like SMOTE, ADASYN, and their variants.
"""

__version__ = "0.1.0"
__author__ = "Diogo Ribeiro"
__email__ = "dfr@esmad.ipp.pt"
__orcid__ = "0009-0001-2022-7072"

from .distance import (
    hassanat_distance,
    distance_matrix,
    minkowski_distance,
    chebyshev_distance,
    mahalanobis_distance,
    canberra_distance,
    hamming_distance,
    jaccard_distance,
    braycurtis_distance,
    correlation_distance,
    energy_distance,
    wasserstein_1d_distance,
    hellinger_distance,
    jensen_shannon_distance,
)
from .validator import (
    validate_oversampling,
    validate_multiclass_oversampling,
    extract_synthetic_samples,
)
from .memory_efficient_validator import MemoryEfficientValidator
from .optimized_distance import OptimizedDistanceMatrix
from .advanced_benchmark import (
    StatisticalBenchmark,
    DatasetRepository,
    create_benchmark_report,
)
from .types import (
    ValidationConfig,
    BenchmarkConfig,
    ValidationMode,
    ValidationResult,
    OversampleQAError,
    ValidationError,
    ConfigurationError,
    MetricError,
)
from .typed_validator import (
    TypedValidator,
    PydanticValidationConfig,
    validation_session,
    registry,
)
from .plugin_system import plugin_manager, register_metric, register_validator
from .metrics import (
    calculate_error_rate,
    confidence_ratio,
    local_density_divergence,
    minority_recall_loss,
    umap_manifold_distance,
    check_model_fairness,
    noise_sensitivity_diagnostic,
)
from .benchmark import (
    load_standard_datasets,
    run_benchmark,
    compute_ranking,
    export_benchmark_results,
)
from .plotting import (
    plot_sample_distribution,
    plot_error_comparison,
    plot_error_boxplot,
    plot_error_ranking,
    plot_error_heatmap,
    plot_noise_sensitivity,
    plot_distance_histogram,
    plot_class_balance,
)
from .report import generate_report
from .clustering import cluster_based_diagnostics
from .surrogate import evaluate_surrogate_models
from .cli import main as cli_main
from .caching import ValidationCache

__all__ = [
    "hassanat_distance",
    "distance_matrix",
    "minkowski_distance",
    "chebyshev_distance",
    "mahalanobis_distance",
    "canberra_distance",
    "hamming_distance",
    "jaccard_distance",
    "braycurtis_distance",
    "correlation_distance",
    "energy_distance",
    "wasserstein_1d_distance",
    "hellinger_distance",
    "jensen_shannon_distance",
    "validate_oversampling",
    "validate_multiclass_oversampling",
    "extract_synthetic_samples",
    "MemoryEfficientValidator",
    "OptimizedDistanceMatrix",
    "ValidationCache",
    "StatisticalBenchmark",
    "DatasetRepository",
    "create_benchmark_report",
    "ValidationConfig",
    "BenchmarkConfig",
    "ValidationMode",
    "ValidationResult",
    "OversampleQAError",
    "ValidationError",
    "ConfigurationError",
    "MetricError",
    "TypedValidator",
    "PydanticValidationConfig",
    "validation_session",
    "registry",
    "plugin_manager",
    "register_metric",
    "register_validator",
    "calculate_error_rate",
    "confidence_ratio",
    "local_density_divergence",
    "minority_recall_loss",
    "umap_manifold_distance",
    "check_model_fairness",
    "noise_sensitivity_diagnostic",
    "run_benchmark",
    "load_standard_datasets",
    "compute_ranking",
    "export_benchmark_results",
    "plot_sample_distribution",
    "plot_error_comparison",
    "plot_error_boxplot",
    "plot_error_ranking",
    "plot_error_heatmap",
    "plot_noise_sensitivity",
    "plot_distance_histogram",
    "plot_class_balance",
    "cluster_based_diagnostics",
    "generate_report",
    "evaluate_surrogate_models",
    "cli_main",
]
