"""
oversampleqa: A diagnostic toolkit for validating oversampling methods.

This package implements validation methods for synthetic data generated by
oversampling techniques like SMOTE, ADASYN, and their variants.
"""

__version__ = "0.5.0"
__author__ = "Diogo Ribeiro"
__email__ = "dfr@esmad.ipp.pt"
__orcid__ = "0009-0001-2022-7072"

from .advanced_benchmark import (
    DatasetRepository,
    StatisticalBenchmark,
    create_benchmark_report,
    format_statistical_summary,
)
from .benchmark import (
    compute_ranking,
    export_benchmark_results,
    load_standard_datasets,
    run_benchmark,
)
from .caching import ValidationCache
from .cli import main as cli_main
from .clustering import cluster_based_diagnostics
from .deprecation import deprecated
from .distance import (
    braycurtis_distance,
    canberra_distance,
    chebyshev_distance,
    correlation_distance,
    distance_matrix,
    energy_distance,
    hamming_distance,
    hassanat_distance,
    hellinger_distance,
    jaccard_distance,
    jensen_shannon_distance,
    mahalanobis_distance,
    minkowski_distance,
    wasserstein_1d_distance,
)
from .estimator import OversamplingValidator, validation_scorer
from .fidelity import (
    BoundaryReport,
    FidelityReport,
    ManifoldMetrics,
    MemorisationReport,
    boundary_violation_rate,
    fidelity_report,
    memorisation_report,
    precision_recall_density_coverage,
)
from .inference import (
    NullCalibration,
    TwoSampleTestResult,
    cross_match_test,
    mst_two_sample_test,
    nn_two_sample_test,
    null_error_rate,
)
from .memory_efficient_validator import MemoryEfficientValidator
from .metrics import (
    calculate_error_rate,
    check_model_fairness,
    confidence_ratio,
    duplication_rate,
    local_density_divergence,
    minority_recall_loss,
    noise_sensitivity_diagnostic,
    umap_manifold_distance,
)
from .optimized_distance import OptimizedDistanceMatrix
from .plotting import (
    plot_class_balance,
    plot_distance_histogram,
    plot_error_boxplot,
    plot_error_comparison,
    plot_error_heatmap,
    plot_error_ranking,
    plot_noise_sensitivity,
    plot_sample_distribution,
)
from .plugin_contract import (
    METRIC_DOMAINS,
    AxiomReport,
    MetricPlugin,
    check_metric_axioms,
)
from .plugin_system import plugin_manager, register_metric, register_validator
from .report import generate_report
from .reports import SCHEMA_VERSION, RunMetadata, ValidationReport
from .surrogate import evaluate_surrogate_models
from .typed_validator import (
    PydanticValidationConfig,
    TypedValidator,
    registry,
    validation_session,
)
from .types import (
    BenchmarkConfig,
    ConfigurationError,
    MetricError,
    OversampleQAError,
    ReferenceSet,
    ValidationConfig,
    ValidationDetails,
    ValidationError,
    ValidationMode,
    ValidationResult,
)
from .validator import (
    extract_synthetic_samples,
    validate_multiclass_oversampling,
    validate_oversampling,
)

__all__ = [
    "METRIC_DOMAINS",
    "SCHEMA_VERSION",
    "AxiomReport",
    "BenchmarkConfig",
    "BoundaryReport",
    "ConfigurationError",
    "DatasetRepository",
    "FidelityReport",
    "ManifoldMetrics",
    "MemorisationReport",
    "MemoryEfficientValidator",
    "MetricError",
    "MetricPlugin",
    "NullCalibration",
    "OptimizedDistanceMatrix",
    "OversampleQAError",
    "OversamplingValidator",
    "PydanticValidationConfig",
    "ReferenceSet",
    "RunMetadata",
    "StatisticalBenchmark",
    "TwoSampleTestResult",
    "TypedValidator",
    "ValidationCache",
    "ValidationConfig",
    "ValidationDetails",
    "ValidationError",
    "ValidationMode",
    "ValidationReport",
    "ValidationResult",
    "boundary_violation_rate",
    "braycurtis_distance",
    "calculate_error_rate",
    "canberra_distance",
    "chebyshev_distance",
    "check_metric_axioms",
    "check_model_fairness",
    "cli_main",
    "cluster_based_diagnostics",
    "compute_ranking",
    "confidence_ratio",
    "correlation_distance",
    "create_benchmark_report",
    "cross_match_test",
    "deprecated",
    "distance_matrix",
    "duplication_rate",
    "energy_distance",
    "evaluate_surrogate_models",
    "export_benchmark_results",
    "extract_synthetic_samples",
    "fidelity_report",
    "format_statistical_summary",
    "generate_report",
    "hamming_distance",
    "hassanat_distance",
    "hellinger_distance",
    "jaccard_distance",
    "jensen_shannon_distance",
    "load_standard_datasets",
    "local_density_divergence",
    "mahalanobis_distance",
    "memorisation_report",
    "minkowski_distance",
    "minority_recall_loss",
    "mst_two_sample_test",
    "nn_two_sample_test",
    "noise_sensitivity_diagnostic",
    "null_error_rate",
    "plot_class_balance",
    "plot_distance_histogram",
    "plot_error_boxplot",
    "plot_error_comparison",
    "plot_error_heatmap",
    "plot_error_ranking",
    "plot_noise_sensitivity",
    "plot_sample_distribution",
    "plugin_manager",
    "precision_recall_density_coverage",
    "register_metric",
    "register_validator",
    "registry",
    "run_benchmark",
    "umap_manifold_distance",
    "validate_multiclass_oversampling",
    "validate_oversampling",
    "validation_scorer",
    "validation_session",
    "wasserstein_1d_distance",
]
