"""Surrogate model evaluation utilities."""

from __future__ import annotations

from typing import Dict

import logging
import numpy as np
from sklearn.base import clone
from sklearn.model_selection import train_test_split
from sklearn.metrics import f1_score, recall_score, precision_score

from .validator import extract_synthetic_samples

logger = logging.getLogger(__name__)


def evaluate_surrogate_models(
    X: np.ndarray,
    y: np.ndarray,
    minority_label: int,
    oversampler,
    model,
    test_size: float = 0.3,
    random_state: int | None = None,
) -> Dict[str, Dict[str, float]]:
    """Evaluate model performance with and without synthetic data.

    The function trains the provided ``model`` under three scenarios:

    1. ``real_only`` – using the original training data without oversampling.
    2. ``real_plus_synth`` – using the oversampled training data.
    3. ``synth_only`` – replacing the real minority samples with the synthetic
       samples generated by the oversampler.

    Parameters
    ----------
    X, y : ndarray
        Input data and labels.
    minority_label : int
        Label of the minority class.
    oversampler : imblearn BaseOverSampler
        Oversampler instance used to generate synthetic samples.
    model : sklearn estimator
        Classifier implementing ``fit``/``predict``.
    test_size : float, default=0.3
        Fraction of the dataset reserved for testing.
    random_state : int, optional
        Random seed for the split.

    Returns
    -------
    dict
        Mapping of scenario names to dictionaries with ``f1``, ``recall`` and
        ``precision`` scores.
    """

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=test_size, stratify=y, random_state=random_state
    )

    # Scenario 1: real-only
    model_real = clone(model)
    model_real.fit(X_train, y_train)
    pred_real = model_real.predict(X_test)

    # Scenario 2: real + synthetic
    oversampler_plus = clone(oversampler)
    try:
        X_res, y_res = oversampler_plus.fit_resample(X_train, y_train)
    except Exception:  # pragma: no cover - defensive
        logger.exception("Oversampler failed during fit_resample")
        raise
    model_plus = clone(model)
    model_plus.fit(X_res, y_res)
    pred_plus = model_plus.predict(X_test)

    # Scenario 3: synthetic-only
    synthetic = extract_synthetic_samples(X_train, X_res, y_res, minority_label)
    majority_mask = y_train != minority_label
    X_majority = X_train[majority_mask]
    y_majority = y_train[majority_mask]
    if len(synthetic) == 0:
        X_syn = X_train
        y_syn = y_train
    else:
        X_syn = np.vstack([X_majority, synthetic])
        y_syn = np.hstack([y_majority, np.full(len(synthetic), minority_label)])
    model_syn = clone(model)
    model_syn.fit(X_syn, y_syn)
    pred_syn = model_syn.predict(X_test)

    def _scores(y_true: np.ndarray, y_pred: np.ndarray) -> Dict[str, float]:
        mask_true = y_true == minority_label
        mask_pred = y_pred == minority_label
        return {
            "f1": f1_score(mask_true, mask_pred),
            "recall": recall_score(mask_true, mask_pred),
            "precision": precision_score(mask_true, mask_pred),
        }

    return {
        "real_only": _scores(y_test, pred_real),
        "real_plus_synth": _scores(y_test, pred_plus),
        "synth_only": _scores(y_test, pred_syn),
    }
