#!/bin/bash

# setup.sh - Environment setup for oversampleqa development
# This script creates a complete development environment for the coding agent

set -e  # Exit on any error

echo "🚀 Setting up oversampleqa development environment..."

# Color codes for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Function to print colored output
print_status() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

print_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Check if Python 3.10+ is available
print_status "Checking Python version..."
python_version=$(python3 -c "import sys; print(f'{sys.version_info.major}.{sys.version_info.minor}')")
required_version="3.10"

if [ "$(printf '%s\n' "$required_version" "$python_version" | sort -V | head -n1)" = "$required_version" ]; then
    print_status "Python $python_version detected ✓"
else
    print_error "Python 3.10+ required, found $python_version"
    exit 1
fi

# Create project directory structure
print_status "Creating project directory structure..."

mkdir -p oversampleqa/{oversampleqa,tests,examples,docs}

# Create main package structure
mkdir -p oversampleqa/oversampleqa

# Create all necessary files
print_status "Creating project files..."

# Create pyproject.toml
cat > oversampleqa/pyproject.toml << 'EOF'
[build-system]
requires = ["setuptools>=45", "wheel", "setuptools_scm[toml]>=6.2"]
build-backend = "setuptools.build_meta"

[project]
name = "oversampleqa"
version = "0.1.0"
description = "A diagnostic toolkit to validate, audit, and benchmark oversampling methods in imbalanced classification tasks."
readme = "README.md"
license = {text = "MIT"}
authors = [
    {name = "Development Team", email = "dev@example.com"}
]
keywords = ["machine-learning", "imbalanced-learning", "oversampling", "smote", "validation"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Science/Research",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
requires-python = ">=3.10"
dependencies = [
    "numpy>=1.19.0",
    "scikit-learn>=1.0.0",
    "imbalanced-learn>=0.8.0",
    "pandas>=1.3.0",
    "matplotlib>=3.3.0",
    "seaborn>=0.11.0",
    "tqdm>=4.60.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=6.0.0",
    "pytest-cov>=2.12.0",
    "black>=21.0.0",
    "isort>=5.9.0",
    "flake8>=3.9.0",
    "mypy>=0.910",
    "pre-commit>=2.15.0",
]
docs = [
    "sphinx>=4.0.0",
    "sphinx-rtd-theme>=0.5.0",
    "nbsphinx>=0.8.0",
    "jupyter>=1.0.0",
]
plotting = [
    "plotly>=5.0.0",
    "umap-learn>=0.5.0",
]
cli = [
    "click>=8.0.0",
    "rich>=10.0.0",
]

[project.urls]
Homepage = "https://github.com/username/oversampleqa"
Documentation = "https://oversampleqa.readthedocs.io/"
Repository = "https://github.com/username/oversampleqa.git"
"Bug Tracker" = "https://github.com/username/oversampleqa/issues"

[project.scripts]
oversampleqa-validate = "oversampleqa.cli:main"

[tool.setuptools.packages.find]
where = ["."]
include = ["oversampleqa*"]

[tool.black]
line-length = 88
target-version = ['py38']
include = '\.pyi?$'

[tool.isort]
profile = "black"
multi_line_output = 3

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = "test_*.py"
python_classes = "Test*"
python_functions = "test_*"
addopts = "-v --tb=short --strict-markers"
markers = [
    "slow: marks tests as slow (deselect with '-m \"not slow\"')",
    "integration: marks tests as integration tests",
]

[tool.coverage.run]
source = ["oversampleqa"]
omit = [
    "*/tests/*",
    "*/test_*",
    "setup.py",
]

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "def __repr__",
    "raise AssertionError",
    "raise NotImplementedError",
]

[tool.mypy]
python_version = "3.10"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
ignore_missing_imports = true
EOF

# Create main package __init__.py
cat > oversampleqa/oversampleqa/__init__.py << 'EOF'
"""
oversampleqa: A diagnostic toolkit for oversampling validation.

This package provides tools to validate synthetic data generated by
oversampling methods like SMOTE, ADASYN, and their variants.
"""

__version__ = "0.1.0"
__author__ = "Development Team"
__email__ = "dev@example.com"

# Import main functions for easy access
from .validator import validate_oversampling
from .distance import hassanat_distance, distance_matrix
from .metrics import calculate_error_rate, confidence_ratio

__all__ = [
    "validate_oversampling",
    "hassanat_distance", 
    "distance_matrix",
    "calculate_error_rate",
    "confidence_ratio",
]
EOF

# Create empty module files
touch oversampleqa/oversampleqa/{distance,validator,metrics,benchmark,plotting,report,cli}.py

# Create test files
cat > oversampleqa/tests/__init__.py << 'EOF'
"""Test suite for oversampleqa package."""
EOF

touch oversampleqa/tests/test_{distance,validator,metrics,benchmark}.py

# Create example files
cat > oversampleqa/examples/basic_validation.py << 'EOF'
"""
Basic validation example for oversampleqa.

This example demonstrates how to validate SMOTE oversampling
using the Hassanat distance-based validation method.
"""

import numpy as np
from sklearn.datasets import make_classification
from imblearn.over_sampling import SMOTE

# This will be implemented by the coding agent
try:
    from oversampleqa import validate_oversampling
    print("✓ oversampleqa imported successfully")
except ImportError as e:
    print(f"✗ Import failed: {e}")
    print("Run this after implementing the package!")

def main():
    """Run basic validation example."""
    print("🔍 Running basic validation example...")
    
    # Create imbalanced dataset
    X, y = make_classification(
        n_samples=1000,
        n_features=20,
        n_informative=10,
        n_redundant=10,
        n_clusters_per_class=1,
        weights=[0.9, 0.1],  # 90-10 class imbalance
        random_state=42
    )
    
    print(f"Dataset shape: {X.shape}")
    print(f"Class distribution: {np.bincount(y)}")
    
    # Validate SMOTE oversampling
    try:
        error_rate = validate_oversampling(
            X=X,
            y=y,
            minority_label=1,
            oversampler=SMOTE(random_state=42),
            hidden_ratio=0.1,
            random_state=42
        )
        
        print(f"🎯 SMOTE validation error rate: {error_rate:.3f}")
        
        if error_rate < 0.1:
            print("✓ Low error rate - SMOTE appears to generate realistic samples")
        elif error_rate < 0.3:
            print("⚠ Moderate error rate - proceed with caution")
        else:
            print("✗ High error rate - synthetic samples may be unrealistic")
            
    except Exception as e:
        print(f"✗ Validation failed: {e}")

if __name__ == "__main__":
    main()
EOF

touch oversampleqa/examples/{benchmark_example,plotting_example}.py

# Create LICENSE file
cat > oversampleqa/LICENSE << 'EOF'
MIT License

Copyright (c) 2024 oversampleqa Development Team

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
EOF

# Create basic test configuration
cat > oversampleqa/pytest.ini << 'EOF'
[tool:pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = -v --tb=short
markers =
    slow: marks tests as slow
    integration: marks tests as integration tests
EOF

# Create .gitignore
cat > oversampleqa/.gitignore << 'EOF'
# Byte-compiled / optimized / DLL files
__pycache__/
*.py[cod]
*$py.class

# C extensions
*.so

# Distribution / packaging
.Python
build/
develop-eggs/
dist/
downloads/
eggs/
.eggs/
lib/
lib64/
parts/
sdist/
var/
wheels/
pip-wheel-metadata/
share/python-wheels/
*.egg-info/
.installed.cfg
*.egg
MANIFEST

# PyInstaller
*.manifest
*.spec

# Installer logs
pip-log.txt
pip-delete-this-directory.txt

# Unit test / coverage reports
htmlcov/
.tox/
.nox/
.coverage
.coverage.*
.cache
nosetests.xml
coverage.xml
*.cover
*.py,cover
.hypothesis/
.pytest_cache/

# Virtual environments
.env
.venv
env/
venv/
ENV/
env.bak/
venv.bak/

# IDEs
.vscode/
.idea/
*.swp
*.swo
*~

# OS
.DS_Store
.DS_Store?
._*
.Spotlight-V100
.Trashes
ehthumbs.db
Thumbs.db

# Project specific
*.log
reports/
plots/
results/
EOF

# Create virtual environment
print_status "Creating virtual environment..."
cd oversampleqa
python3 -m venv venv

# Activate virtual environment and install dependencies
print_status "Installing dependencies..."
source venv/bin/activate

# Upgrade pip and install build tools
python -m pip install --upgrade pip setuptools wheel

# Install core dependencies
pip install numpy>=1.19.0 scikit-learn>=1.0.0 imbalanced-learn>=0.8.0

# Install additional dependencies
pip install pandas>=1.3.0 matplotlib>=3.3.0 seaborn>=0.11.0 tqdm>=4.60.0

# Install development dependencies
pip install pytest>=6.0.0 pytest-cov>=2.12.0 black>=21.0.0 isort>=5.9.0 flake8>=3.9.0

# Install optional dependencies
pip install plotly>=5.0.0 click>=8.0.0 rich>=10.0.0

# Install package in development mode
pip install -e .

print_status "Testing installation..."
python -c "import numpy, sklearn, imblearn; print('✓ Core dependencies working')"

# Create development helper scripts
cat > dev_setup.py << 'EOF'
#!/usr/bin/env python3
"""Development setup helper script."""

import subprocess
import sys

def run_tests():
    """Run the test suite."""
    print("🧪 Running tests...")
    subprocess.run([sys.executable, "-m", "pytest", "tests/", "-v"])

def format_code():
    """Format code with black and isort."""
    print("🎨 Formatting code...")
    subprocess.run([sys.executable, "-m", "black", "oversampleqa/", "tests/", "examples/"])
    subprocess.run([sys.executable, "-m", "isort", "oversampleqa/", "tests/", "examples/"])

def lint_code():
    """Lint code with flake8."""
    print("🔍 Linting code...")
    subprocess.run([sys.executable, "-m", "flake8", "oversampleqa/", "tests/"])

def run_example():
    """Run basic example."""
    print("🚀 Running basic example...")
    subprocess.run([sys.executable, "examples/basic_validation.py"])

if __name__ == "__main__":
    if len(sys.argv) > 1:
        command = sys.argv[1]
        if command == "test":
            run_tests()
        elif command == "format":
            format_code()
        elif command == "lint":
            lint_code()
        elif command == "example":
            run_example()
        else:
            print(f"Unknown command: {command}")
            print("Available commands: test, format, lint, example")
    else:
        print("Available commands: test, format, lint, example")
        print("Usage: python dev_setup.py <command>")
EOF

chmod +x dev_setup.py

cd ..

print_status "Creating activation script..."
cat > activate_env.sh << 'EOF'
#!/bin/bash
# Activation script for oversampleqa development environment

echo "🚀 Activating oversampleqa development environment..."
cd oversampleqa
source venv/bin/activate

echo "✓ Environment activated!"
echo "📁 Current directory: $(pwd)"
echo "🐍 Python version: $(python --version)"
echo "📦 Pip version: $(pip --version)"

echo ""
echo "🛠️  Available development commands:"
echo "  python dev_setup.py test      # Run tests"
echo "  python dev_setup.py format    # Format code"
echo "  python dev_setup.py lint      # Lint code"
echo "  python dev_setup.py example   # Run basic example"
echo ""
echo "📚 Quick start:"
echo "  1. Implement core modules in oversampleqa/"
echo "  2. Run: python examples/basic_validation.py"
echo "  3. Run: python dev_setup.py test"
echo ""
echo "📖 See AGENTS.md for detailed implementation instructions"
EOF

chmod +x activate_env.sh

# Final summary
print_status "Environment setup complete! 🎉"
echo ""
echo -e "${BLUE}📁 Project structure created in: ./oversampleqa/${NC}"
echo -e "${BLUE}🐍 Virtual environment: ./oversampleqa/venv/${NC}"
echo ""
echo -e "${GREEN}Next steps:${NC}"
echo "1. Run: ${YELLOW}source activate_env.sh${NC}"
echo "2. Follow implementation guide in AGENTS.md"
echo "3. Start with core modules: distance.py, validator.py, metrics.py"
echo ""
echo -e "${GREEN}Development workflow:${NC}"
echo "• ${YELLOW}python dev_setup.py test${NC}     - Run tests"
echo "• ${YELLOW}python dev_setup.py format${NC}   - Format code"
echo "• ${YELLOW}python dev_setup.py example${NC}  - Run example"
echo ""
echo -e "${GREEN}Quick validation:${NC}"
echo "• Run: ${YELLOW}cd oversampleqa && source venv/bin/activate${NC}"
echo "• Then: ${YELLOW}python -c \"import oversampleqa; print('✓ Package ready!')\"${NC}"
echo ""
print_status "Happy coding! 🚀"
